apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  labels:
    app: todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/data/metrics'
        prometheus.io/port: '80'        
    spec:
      containers:
      - name: todo-api-container
        image: registry.local:5000/training/todo-api:latest
        env:
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: config
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: config
                key: DB_USER                
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "todo-postgresql"
                key: "postgres-password"        
        ports:
        - containerPort: 8080