apiVersion: v1
kind: Service
metadata:
  name: todo-api-svc
  labels:
    app: todo-api
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/data/metrics'
    prometheus.io/port: '80'      
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: todo-api