apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  labels:
    app: todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api     
    spec:
      containers:
      - name: todo-api-container
        image: registry.local:5000/training/todo-api:latest
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: todo-api-config
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: todo-api-config
                key: DB_USER                
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "todo-postgresql"
                key: "postgres-password"        
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m